#!/bin/bash

set -e

TARGET=$1

# packages
sudo apt update -qq
sudo apt install -y --no-install-recommends \
  automake \
  bison \
  bzip2 \
  ca-certificates \
  curl \
  file \
  flex \
  g++ \
  gawk \
  gdb \
  git \
  gperf \
  help2man \
  libncurses-dev \
  libssl-dev \
  libtool-bin \
  make \
  patch \
  pkg-config \
  python3 \
  rsync \
  texinfo \
  unzip \
  wget \
  xz-utils

# patch
pushd builder
for i in ../targets/${TARGET}/*; do
    if [[ $i == *.patch ]]; then
        patch -Np1 -i $i
    fi
done
popd

# crosstool-ng
if [ ! -e /usr/bin/ct-ng ]; then
    pushd builder
    ./bootstrap
    ./configure --prefix=/usr
    make -j`nproc`
    sudo make install
    popd
fi

# build
sudo mkdir -p /opt
sudo chmod 0777 /opt
mkdir -p build
cp targets/${TARGET}/config build/.config
pushd build
ct-ng olddefconfig
ct-ng build
popd

# tarball
XZ_OPT="-9 -T0" tar -C /opt/x-tools --owner=0 --group=0 --numeric-owner -cJvf ${TARGET}.tar.xz ${TARGET}
