name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    env:
      tag_name: latest
    runs-on: ubuntu-latest
    steps:
      - name: GH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "RUN_ID=$(gh run list --json databaseId --workflow build.yml --limit 1 -q '.[0].databaseId' -R ${{ github.repository }})" >> $GITHUB_ENV
          echo "DATE=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --jq '.commit.committer.date' | date -f - +%Y%m%d)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ env.RUN_ID }}

      - name: Generate checksums
        run: |
          find ./release -type f -name '*.tar.xz' -exec mv {} . \;
          rm -rf release
          printf "| %s | %s |\n" Filename "sha256sum" --- --- > body.txt
          for i in *.tar.xz ; do
            printf "| %s | %s |\n" "$i" $(sha256sum $i | tee -a sha256sums.txt | awk '{print $1}') >> body.txt
          done

      - name: Delete existing release
        if: false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ env.tag_name }} --cleanup-tag -y -R ${{ github.repository }} || true

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: false
          tag_name: ${{ env.tag_name }}
          name: ${{ env.DATE }}
          body_path: body.txt
          files: |
            *.tar.xz
            sha256sums.txt
